name: Android CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check with Gradle
      run: chmod +x ./gradlew && ./gradlew check
    - name: Test with Gradle
      run: chmod +x ./gradlew && ./gradlew test
    - name: Coverage with Gradle
      run: chmod +x ./gradlew && ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
        flags: unittests

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod +x ./gradlew && ./gradlew build
